<a href="https://colab.research.google.com/github/timfitz04/Business-Analytics-Dissertation/blob/main/CorkWS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://gaacork.ie/competition-listing/

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.chdir("/content/drive/MyDrive/Dissertation/Cork")
!pwd

/content/drive/MyDrive/Dissertation/Cork

In [ ]:
!pip install bs4

Requirement already satisfied: bs4 in /usr/local/lib/python3.12/dist-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)

In [ ]:
from bs4 import BeautifulSoup
import http.client
import urllib.request
import pandas as pd
import time
import re
time.sleep(5)
urls = {
   2025:[
    ("https://gaacork.ie/league/201198/?user_id=7", "Division 1"),
    ("https://gaacork.ie/league/201200/?user_id=7", "Division 2"),
    ("https://gaacork.ie/league/201203/?user_id=7", "Division 3"),
    ("https://gaacork.ie/league/201204/?user_id=7", "Division 4"),
    ("https://gaacork.ie/league/201206/?user_id=7", "Division 5"),
    ("https://gaacork.ie/league/201209/?user_id=7", "Division 6"),
    ("https://gaacork.ie/league/201215/?user_id=7", "Division 7")
    ],
   2024:[
    ("https://gaacork.ie/league/190310/?user_id=7", "Division 1"),
    ("https://gaacork.ie/league/190311/?user_id=7", "Division 2"),
    ("https://gaacork.ie/league/190312/?user_id=7", "Division 3"),
    ("https://gaacork.ie/league/190314/?user_id=7", "Division 4"),
    ("https://gaacork.ie/league/190315/?user_id=7", "Division 5"),
    ("https://gaacork.ie/league/190316/?user_id=7", "Division 6"),
    ("https://gaacork.ie/league/190317/?user_id=7", "Division 7")
    ],
   2023:[
    ("https://gaacork.ie/league/177746/?user_id=7", "Division 1"),
    ("https://gaacork.ie/league/177747/?user_id=7", "Division 2"),
    ("https://gaacork.ie/league/177748/?user_id=7", "Division 3"),
    ("https://gaacork.ie/league/177743/?user_id=7", "Division 4"),
    ("https://gaacork.ie/league/177750/?user_id=7", "Division 5"),
    ("https://gaacork.ie/league/177751/?user_id=7", "Division 6"),
    ("https://gaacork.ie/league/177752/?user_id=7", "Division 7")
   ],
   2022: [
      ("https://gaacork.ie/league/167824/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/167826/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/167828/?user_id=7", "Division 3")
   ],
   2021: [
      ("https://gaacork.ie/league/157318/?user_id=7", "Division 1A"),
      ("https://gaacork.ie/league/157319/?user_id=7", "Division 1B"),
      ("https://gaacork.ie/league/157320/?user_id=7", "Division 2A"),
      ("https://gaacork.ie/league/157321/?user_id=7", "Division 2B"),
      ("https://gaacork.ie/league/157322/?user_id=7", "Division 3A"),
      ("https://gaacork.ie/league/157323/?user_id=7", "Division 3B"),
      ("https://gaacork.ie/league/157324/?user_id=7", "Division 4A"),
      ("https://gaacork.ie/league/157325/?user_id=7", "Division 4B"),
      ("https://gaacork.ie/league/157326/?user_id=7", "Division 5A"),
      ("https://gaacork.ie/league/157328/?user_id=7", "Division 5B"),
      ("https://gaacork.ie/league/157329/?user_id=7", "Division 6A"),
      ("https://gaacork.ie/league/157331/?user_id=7", "Division 6B"),
      ("https://gaacork.ie/league/157332/?user_id=7", "Division 7")
   ],
   2019: [
      ("https://gaacork.ie/league/135975/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/136032/?user_id=7", "Division 4"),
      ("https://gaacork.ie/league/136038/?user_id=7", "Division 5")
   ],
   2018: [
      ("https://gaacork.ie/league/125200/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/125214/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/125213/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/125215/?user_id=7", "Division 4"),
      ("https://gaacork.ie/league/125221/?user_id=7", "Division 5")
   ],
   2017: [
      ("https://gaacork.ie/league/114419/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/114420/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/114472/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/114473/?user_id=7", "Division 4"),
      ("https://gaacork.ie/league/114474/?user_id=7", "Division 5")
   ],
   2016: [
      ("https://gaacork.ie/league/104224/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/104225/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/104226/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/104227/?user_id=7", "Division 4")
   ],
   2015: [
      ("https://gaacork.ie/league/92069/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/92078/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/92148/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/92155/?user_id=7", "Division 4")
   ],
   2014: [
      ("https://gaacork.ie/league/74469/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/74745/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/74743/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/74741/?user_id=7", "Division 4")
   ],
   2013: [
      ("https://gaacork.ie/league/59887/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/59889/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/59891/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/59893/?user_id=7", "Division 4")
   ],
   2012: [
      ("https://gaacork.ie/league/29665/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/29669/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/29675/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/29679/?user_id=7", "Division 4")
   ],
   2011: [
      ("https://gaacork.ie/league/19323/?user_id=7", "Division 1"),
      ("https://gaacork.ie/league/19325/?user_id=7", "Division 2"),
      ("https://gaacork.ie/league/19327/?user_id=7", "Division 3"),
      ("https://gaacork.ie/league/19329/?user_id=7", "Division 4")
   ]
}

all_data = []

for year, url_list in urls.items():
    for url, base_division in url_list:

        response = urllib.request.urlopen(url)
        raw_html = response.read().decode("utf-8")
        document = BeautifulSoup(raw_html, 'html.parser')

        # Find all headers & tables (groups)
        headers = document.find_all("h3")
        tables = document.find_all("table", {"class": "league_table table-condensed table-responsive table"})

        for header, table in zip(headers, tables):

            group_name = header.get_text(strip=True)

            # group_name looks like: "Division 1 - Group A"
            if "Group" in group_name:
                group_letter = group_name.split("Group")[-1].strip()
                division_name = f"{base_division}{group_letter}"    # Division 1A, Division 1B etc.
            else:
                division_name = base_division   # If no groups found

            rows = table.find_all("tr")[2:]  # skip header rows
            for row in rows:
                cells = row.find_all("td")

                data = {
                    "County": "Cork",
                    "Division": division_name,
                    "Year": year,
                    "team": cells[1].get_text(strip=True),
                    "pld":  cells[2].get_text(strip=True),
                    "w":    cells[3].get_text(strip=True),
                    "d":    cells[4].get_text(strip=True),
                    "l":    cells[5].get_text(strip=True),
                    "pf":   cells[6].get_text(strip=True),
                    "pa":   cells[7].get_text(strip=True),
                    "pd":   cells[8].get_text(strip=True),
                    "pts":  cells[9].get_text(strip=True)
                }

                all_data.append(data)

Cork = pd.DataFrame(all_data)
print(Cork)

    County    Division  Year            team pld  w  d  l   pf   pa   pd pts
0     Cork  Division 1  2025     St Finbarrs   9  8  0  1  144  133   11  16
1     Cork  Division 1  2025      Clonakilty   9  7  1  1  188  125   63  15
2     Cork  Division 1  2025    Nemo Rangers   9  7  0  2  142  121   21  14
3     Cork  Division 1  2025         Douglas   9  4  1  4  106  106    0   9
4     Cork  Division 1  2025  Cill na Martra   9  4  1  4  151  152   -1   9
..     ...         ...   ...             ...  .. .. .. ..  ...  ...  ...  ..
737   Cork  Division 4  2011         Canovee  12  3  2  7  173  184  -11   8
738   Cork  Division 4  2011    Aghabullogue  12  2  2  8  127  146  -19   6
739   Cork  Division 4  2011          Cloyne  10  2  1  7  111  146  -35   5
740   Cork  Division 4  2011     Killavullen   9  1  1  7   70  140  -70   3
741   Cork  Division 4  2011     Ballyclough  10  0  2  8   95  190  -95   2

[742 rows x 12 columns]

In [ ]:
Cork.to_csv('Cork_gaa_leagues.csv', index=False)

In [ ]:
Cork = pd.read_csv("Cork_gaa_leagues.csv")

In [ ]:
def clean_club_name(name):
    name = name.lower()

    # remove trailing numbers (Thomas Davis 2 → Thomas Davis)
    name = re.sub(r"\s*\d+$", "", name)

    # remove reserve/second team indicators e.g. "2nd", "B", "C"
    name = re.sub(r"\b(2nd|second|team|b|c)\b", "", name, flags=re.IGNORECASE)

    # strip GAA-specific suffixes and organisation labels
    name = re.sub(r"\b(gaa|clg|club|lgfa|ladies)\b", "", name, flags=re.IGNORECASE)

    # remove punctuation + multiple spaces
    name = re.sub(r"[^\w\s]", "", name)
    name = " ".join(name.split())
    return name.strip()

# after scraping into Dub dataframe:
Cork["clean_team"] = Cork["team"].apply(clean_club_name)

In [ ]:
display(Cork)

,County,Division,Year,team,pld,w,d,l,pf,pa,pd,pts,clean_team
0,Cork,Division 1,2025,St Finbarrs,9,8,0,1,144,133,11,16,st finbarrs
1,Cork,Division 1,2025,Clonakilty,9,7,1,1,188,125,63,15,clonakilty
2,Cork,Division 1,2025,Nemo Rangers,9,7,0,2,142,121,21,14,nemo rangers
3,Cork,Division 1,2025,Douglas,9,4,1,4,106,106,0,9,douglas
4,Cork,Division 1,2025,Cill na Martra,9,4,1,4,151,152,-1,9,cill na martra
...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,Cork,Division 4,2011,Canovee,12,3,2,7,173,184,-11,8,canovee
738,Cork,Division 4,2011,Aghabullogue,12,2,2,8,127,146,-19,6,aghabullogue
739,Cork,Division 4,2011,Cloyne,10,2,1,7,111,146,-35,5,cloyne
740,Cork,Division 4,2011,Killavullen,9,1,1,7,70,140,-70,3,killavullen
741,Cork,Division 4,2011,Ballyclough,10,0,2,8,95,190,-95,2,ballyclough

In [ ]:
coords = pd.read_csv("gaapitchfinder_data.csv")
coords["clean_team"] = coords["Club"].apply(clean_club_name)
coords = coords[coords["County"] == "Cork"].copy()
coords = coords.drop_duplicates(
    subset="clean_team",
    keep="first"
)
coords = coords[["clean_team", "Latitude", "Longitude"]]

coords

          clean_team   Latitude  Longitude
226             cork  51.899808  -8.435337
957         adrigole  51.684475  -9.712323
958     aghabullogue  51.906736  -8.786975
959           aghada  51.847754  -8.193244
960         aghinagh  51.938635  -8.906060
...              ...        ...        ...
1116   valley rovers  51.785103  -8.691404
1117  watergrasshill  52.021206  -8.337165
1118    whites cross  51.953689  -8.440310
1119     whitechurch  51.982503  -8.531731
1120         youghal  51.952536  -7.860442

[159 rows x 3 columns]

In [ ]:
manual_map ={
    "eire og":"éire óg",
    "béal áthan ghaorthaidh":"béal athan ghaorthaidh",
    "glanworth":"glanworthharbour rovers",
    "uibh laoire":"iveleary",
    "naomh aban":"naomh abán",
    "dromtarriffe":"dromtariffe",
    "st nicks":"st nicholas",
    "liscarrollchurchtown gaels": "churchtown"
    #"beara":
}
Cork["clean_team"] = Cork["clean_team"].replace(manual_map)

In [ ]:
Cork = Cork.merge(coords, on=["clean_team"], how="left")

In [ ]:
Cork[Cork["Latitude"].isna()][["team","clean_team"]].drop_duplicates()

      team clean_team
715  Beara      beara

In [ ]:
Cork.to_csv('Cork_gaa_leagues.csv', index=False)